platform :ios, '14.0'

target 'RedsRacing' do
  use_frameworks!

  # Firebase - pin to stable versions
  pod 'FirebaseCore', '~> 10.18.0'
  pod 'FirebaseAuth', '~> 10.18.0'
  pod 'FirebaseMessaging', '~> 10.18.0'
  pod 'FirebaseFirestore', '~> 10.18.0'
  
  # Google Mobile Ads SDK
  pod 'Google-Mobile-Ads-SDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      # Disable code signing for Pod targets
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
