platform :ios, '14.0'

target 'RedsRacing' do
  use_frameworks!

  # Firebase - latest version for better Xcode compatibility
  pod 'FirebaseCore', '~> 11.0'
  pod 'FirebaseAuth', '~> 11.0'
  pod 'FirebaseMessaging', '~> 11.0'
  pod 'FirebaseFirestore', '~> 11.0'
  
  # Google Mobile Ads SDK
  pod 'Google-Mobile-Ads-SDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      # Disable code signing for ALL Pod targets
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
    end
  end
end
