# .github/workflows/firebase-deploy.yml
name: Deploy to Firebase Hosting & Functions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  # --- PREVIEW (PRs) — Hosting only ---
  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Install Node.js Functions Dependencies
        run: npm ci --prefix functions
      - name: Install Python Functions Dependencies
        run: pip install -r functions_python/requirements.txt
      - name: Deploy to Firebase Hosting preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REDS_RACING_A7F8B }}
          projectId: redsracing-a7f8b
          channelId: 'pr-${{ github.event.number }}-${{ github.sha }}'

  # --- PRODUCTION (main) — Hosting LIVE + Functions ---
  production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Install Node.js Functions Dependencies
        run: npm ci --prefix functions
      - name: Install Python Functions Dependencies
        run: pip install -r functions_python/requirements.txt
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REDS_RACING_A7F8B }}
          projectId: redsracing-a7f8b
          channelId: live
